### ISSUE TITLE
Please add {"type": "module"} to package.json

### ISSUE THREAD

**Issue by seyyidt** [chris-m92/react-leaflet-custom-control#11]
I get this error when I simply try to import the module:
SyntaxError: Cannot use import statement outside a module.

The solution is pretty easy, just add to package.json:
`"type": "module"`

**Comment by aamuzakii** [comment]
same issue here when running jest
![image](https://github.com/chris-m92/react-leaflet-custom-control/assets/69757282/35a36be8-a4ea-47e8-b5d1-400cfe6fb8c5)

**Comment by chris-m92** [comment]
Closed and updated - Sorry it took a minute to get to this.
