### ISSUE TITLE
Scrolling in control, moves map, instead of scroll the control container

### ISSUE THREAD

**Issue by guptaashwanee** [chris-m92/react-leaflet-custom-control#13]
I have a list of components rendering in this custom leaflet control, this is a long list, I want this to be scrollable, but instead of scrolling inside components of this custom leaflet control, map is moving.

**Comment by MrRainesE** [comment]
@guptaashwanee I was facing the same issue but this is resolved in the latest version. here is a working sanbox https://codesandbox.io/s/react-leaflet-custom-control-forked-su7qdv?file=/src/App.tsx
