### ISSUE TITLE
Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

### ISSUE THREAD

**Issue by Phillip2025** [chris-m92/react-leaflet-custom-control#14]
When hiding a control the app crashes showing the mentioned error. I checked with old versions and the bug starts to appear on the 1.3.2 version, up to the newest 1.3.4

I already created a codesandbox with a check to hide the control and make the bug to appear: https://codesandbox.io/s/react-leaflet-custom-control-forked-pgkqfe?file=/package.json

To see the right behaviour, change the version of the package to 1.3.1 and uncheck again

**Comment by chris-m92** [comment]
@Phillip2025,
I'm sorry you've been running into this issue. `v1.3.2` fixed an issue that caused recurring `<div>` tags to be constantly added to the DOM on each render. I checked out your CSB, thanks for building that. A workaround is to not remove the `<Control>` component, but remove the children of `<Control>`. You won't run into crashes on `^1.3.2` any more.

For example, from your code, 

```ts
<Control position="topright">
  {checked && (
    <ButtonGroup orientation="vertical" variant="contained">
      <Tooltip placement="left" title="Fullscreen"> 
        <Button color="inherit">
          <FullscreenIcon />
        </Button>
      </Tooltip>
    </ButtonGroup>
  )}
</Control>
```

**Comment by Phillip2025** [comment]
Thanks for the response, it works perfectly this way
