### ISSUE TITLE
Doesn't work properly for more than one map

### ISSUE THREAD

**Issue by brlatdmidotdk** [chris-m92/react-leaflet-custom-control#17]
In a use case where you want to show more maps at the same time all controls will end up in the first map.

The error is due to the way the portal root is found by always using index 0.

**Comment by KoenBrouwer** [comment]
We're experiencing the same issue, where indeed on a page with multiple maps, the controls all appear in the first map. I hoped that I could fix this by using the `container` prop, but documentation is not clear on how to use it. 

@chris-m92 Can you help?

**Comment by chris-m92** [comment]
@KoenBrouwer,

I'll take a look. Full disclosure, I haven't looked at or used this package in some time, and moved to a different solution for my own leaflet maps.

**Comment by chris-m92** [comment]
Great news, I figured out a fix for this issue. I'll be updating the github repo and npm shortly. 
Specifically for this issue.

As far as @KoenBrouwer's question regarding the use of the `container` prop. Honestly, I can't fully recall. I think that was based on a PR that someone else had that fixed an issue for them. It looks like all it realistically does is forward the `container.className` into the Control's div container, most likely for styling purposes.

**Comment by chris-m92** [comment]
@KoenBrouwer , @brlatdmidotdk . `v1.4.0` is now published on npmjs. Let me know if that works for you. It worked in my codesandbox testing arena where the controls were added to the different maps, not just the first map on the page.

**Comment by KoenBrouwer** [comment]
> @KoenBrouwer,
> 
> I'll take a look. Full disclosure, I haven't looked at or used this package in some time, and moved to a different solution for my own leaflet maps.

Thanks for looking into this so quickly! We now moved on by using the default controls, but once your change has come through on NPM, I'll see if I can make it work. Thanks again! 🙏🏻
