### ISSUE TITLE
Upgrade React peerDependency

### ISSUE THREAD

**Issue by MLNW** [chris-m92/react-leaflet-custom-control#3]
React v18 has been released about 3 weeks ago: https://reactjs.org/blog/2022/03/29/react-v18.html

Would it be possible to upgrade the peerDependencies for this package to target this new version?

**Comment by chris-m92** [comment]
@MLNW - Thanks for reaching out, I just updated all the peer dependencies for `react` and `react-dom`, thanks for bringing it up to my attention.
