### ISSUE TITLE
Change peer dependencies

### ISSUE THREAD

**Issue by karasma3** [chris-m92/react-leaflet-custom-control#4]
Hello @chris-m92 , in #3 you changed peer deps and now it requires to have React 18 installed. Would it be possible to have the peer dependencie as follows? I dont want to use `--legacy-peer-deps` in my project and it seems like this package is operational on both React 17 and 18.
```
  "peerDependencies": {
    "leaflet": "^1.7.1",
    "react": ">=17.0.2",
    "react-dom": ">=17.0.2"
  },
```
or
```
  "peerDependencies": {
    "leaflet": "^1.7.1",
    "react": "^17.0.2 || ^18.0.0||^18.1.0",
    "react-dom": "^17.0.2 || ^18.0.0||^18.1.0"
  },
```

**Comment by chris-m92** [comment]
Should be taken care of for you and react 17. If you run into issues, let me know.

Also updated README to mention `React.creatPortal` quirks in ordering components and my recommendations to prevent that.
