### ISSUE TITLE
Creates new div element every render?

### ISSUE THREAD

**Issue by samiamlabs** [chris-m92/react-leaflet-custom-control#5]
Hi!

Thanks for making this component, it's nice to be able to put custom buttons and things among the standard leaflet controls!

I noticed that the component seemed to create new `div` elements for every new render. I was causing some issues in _isClickDisabled from leaflets Map.js after the first re-render and was making some buttons not work for me. I did a quick rewrite that seems to have fixed it.

I did not really understand the reason for the portals thought, and feel like I might be missing something :)

Here is the code:

```js
import React from 'react';

const POSITION_CLASSES = {
  bottomleft: 'leaflet-bottom leaflet-left',
  bottomright: 'leaflet-bottom leaflet-right',
  topleft: 'leaflet-top leaflet-left',
  topright: 'leaflet-top leaflet-right',
}

const Control = (props) => {
  const [portalRoot, setPortalRoot] = React.useState(null);
  const controlContainerRef = React.createRef();
  const positionClass = ((props.position && POSITION_CLASSES[props.position]) || POSITION_CLASSES.topright)

  React.useEffect(() => {
    const targetDiv = document.getElementsByClassName(positionClass)
    setPortalRoot(targetDiv[0])

  }, [positionClass])

  React.useEffect(() => {
    if (portalRoot !== null) {
      if (props.prepend !== undefined && props.prepend === true && portalRoot !== null) {
        portalRoot.prepend(controlContainerRef.current);
      } else {
        portalRoot.append(controlContainerRef.current);
      }
    }
  }, [portalRoot, props.prepend, controlContainerRef]);

  return (
    <div ref={controlContainerRef} className='leaflet-control leaflet-bar' style={props.style}>{props.children}</div>
  );
}

export default Control
```

Do you see any issues with this approach?

**Comment by FranciscoKloganB** [comment]
Got the same issue;

Could the approach proposed by @[samiamlabs](https://github.com/samiamlabs) be tested in the main repo?

It is not something that bothers me too much. I only display the map with these kinds of controls on a single, very particular, use-case and only when a user wants to set an address via map instead of coordinate inputs fields.

But I think it is a worthwhile optimization for other users.

![image](https://user-images.githubusercontent.com/25959244/173060385-1673eb56-b60b-472b-8d22-cb082d2684ec.png)

**Comment by chris-m92** [comment]
Sorry I've been AFK for a bit. Between work and school I haven't been able to take a look at this. Definitely interesting that it's not appropriately "Portal-ing" into the div that should already exist. I can check it out. @samiamlabs I'm not seeing the same behavior where it's creating new divs on each render but I'll look into it.

**Comment by rbertucat** [comment]
I have the same 2 issues as reported here:

1. the multiple div on each render
2. the _isClickDisabled in the console

```
Uncaught TypeError: Cannot read properties of null (reading '_leaflet_disable_click')
    at NewClass._isClickDisabled (leaflet-src.js?2f88:4350:1)
    at NewClass._handleDOMEvent (leaflet-src.js?2f88:4357:1)
    at HTMLDivElement.handler (leaflet-src.js?2f88:2692:1)
_isClickDisabled @ leaflet-src.js?2f88:4350
_handleDOMEvent @ leaflet-src.js?2f88:4357
handler @ leaflet-src.js?2f88:2692
```

**Comment by chris-m92** [comment]
@rbertucat 

I'm checking out the div issue right now. 

Regarding the `_isClickDisabled` console error, I've been getting them too. I think that's a factor of `leaflet@1.8.0` and the changes they made with click propagation. I've not noticed any breaking behavior or crashes because of the error, however. And it doesn't show in production.

**Comment by Babeev** [comment]
I have corrected the code for my purposes. The bugs disappeared, but I didn't test it well enough. Perhaps it will be useful to someone.

**Comment by Babeev** [comment]
I have corrected the code for my purposes. The bugs disappeared, but I didn't test it well enough. Perhaps it will be useful to someone.

```
import React, { memo, ReactElement, useEffect, useRef } from 'react'
import ReactDOM from 'react-dom'
import L from 'leaflet'

interface ControlProps {
  position: L.ControlPosition
  children?: React.ReactNode
  style?: React.CSSProperties
  prepend?: boolean
}

const POSITION_CLASSES: Record<L.ControlPosition, string> = {
  bottomleft: 'leaflet-bottom leaflet-left',
  bottomright: 'leaflet-bottom leaflet-right',
  topleft: 'leaflet-top leaflet-left',
  topright: 'leaflet-top leaflet-right',
}

export const Control = memo(
  ({ position, children, style, prepend }: ControlProps): ReactElement => {
    const [portalRoot, setPortalRoot] = React.useState<HTMLDivElement>(
      document.createElement('div')
    )
    const controlContainerRef = useRef<HTMLDivElement | null>(null)

    useEffect(() => {
      const positionClass =
        POSITION_CLASSES[position] || POSITION_CLASSES.topright

      const targetDiv = document.getElementsByClassName(positionClass)

      setPortalRoot(targetDiv[0] as HTMLDivElement)
    }, [position])

    useEffect(() => {
      if (portalRoot && controlContainerRef.current) {
        if (prepend) {
          portalRoot.prepend(controlContainerRef.current)
        } else {
          portalRoot.append(controlContainerRef.current)
        }

        L.DomEvent.disableClickPropagation(portalRoot)
      }
    }, [prepend, portalRoot])

    const controlContainer = (
      <div
        ref={controlContainerRef}
        className="leaflet-control leaflet-bar"
        style={style}
      >
        {children}
      </div>
    )

    return ReactDOM.createPortal(controlContainer, portalRoot)
  }
)
```

**Comment by ardaicoz** [comment]
I'm also having this problem. I tried to implement the solutions of both @samiamlabs and @Babeev but it doesn't seem to change anything. Should I only change the .tsx file in the src directory or does the lib directory needs some change as well?

**Comment by Kreachers** [comment]
I also was having this problem where div's were constantly being appended. In my project, it looks like a rerender in the parent component of the Control would cause the control append more divs. I was able to work around this by keeping any rerender within a child component. 

```
import { TextField } from '@mui/material';
import { FunctionComponent, ReactElement, useEffect, useState } from 'react';

export const TempComp: FunctionComponent = (): ReactElement => {
  const [first, setfirst] = useState<number>(0);

  useEffect(() => {
    const interval = setInterval(() => setfirst(first + 1), 5000);
    return (): void => clearInterval(interval);
  }, [first]);

  return (
    <div className={"h-40 w-40 text-4xl"}>
      {first}
      <TextField />
    </div>
  );
};
```
```
const TempComp: FunctionComponent = (): ReactElement => {
  return (
    <MapContainer {...MapContainerProps}>
      <Control position="topleft">
        <TempComp />
      </Control>
      {...OtherMapStuff}
    </MapContainer>
  );
};
```

Structuring our components something like this fixed the div appending. Before, everything that is in the TempComp was in the main mapContainer causing constant rerenders.

**Comment by kocunop** [comment]
Problem in create portalContainer every render.

I fix problem with add unique key on control props and use it as Id to portal container.

```
...
let portalContainer = document.getElementById(containerKey);
    
if (!portalContainer) {
    portalContainer = document.createElement('div');
    portalContainer.setAttribute('id', containerKey);
}
...
```
