### ISSUE TITLE
Only one map component supported

### ISSUE THREAD

**Issue by jurvei** [chris-m92/react-leaflet-custom-control#6]
When using two independent map components on a single page, all controls are rendered into the first one.

The reason is pretty obvious:
```
const targetDiv = document.getElementsByClassName(positionClass) // will find multiple elements
setPortalRoot(targetDiv[0]) // but always the first is used
```

I solved it by passing a reference to the parent element and execute getElementsByClassName on that base.
```
const targetDiv = (props.mapContainerRef?.current ?? document).getElementsByClassName(positionClass)
setPortalRoot(targetDiv[0])
```

**Comment by chris-m92** [comment]
Fixed in `v1.3.0` - Thanks to a PR, there is now an optional `container` prop to pass the target portal container. Hopefully this will fix your issue.
