### ISSUE TITLE
Lazy loaded map returns 504 error

### ISSUE THREAD

**Issue by charlieforward9** [chris-m92/react-leaflet-custom-control#9]
When attempting to add controls to my map, it kept crashing the app, I found [this issue](https://github.com/storybookjs/builder-vite/issues/439) that helped me determine I needed to declare the file where the controls are declared in my `vite.config.ts` file to pre-bundle it and ensure it loads. 

Below is the code I used for my project that depends on **vite** & [**vite-plugin-ssr**](https://github.com/brillout/vite-plugin-ssr). 

This would be helpful to put in the docs for anyone who needs to lazy load the component on a SSR application.

```import react from '@vitejs/plugin-react'
import ssr from 'vite-plugin-ssr/plugin'
/** @type {import('vite').UserConfig} */

export default {
  plugins: [react(), ssr()],
  optimizeDeps: {
    //To ensure the map loads with the controllers
    include: ['src/components/Map.tsx'], 
  },
}
```

**Comment by charlieforward9** [comment]
@brillout maybe this issue would also be relevant to have in [vite-plugin-ssr docs](https://github.com/brillout/vite-plugin-ssr) . Food for thought.

**Comment by brillout** [comment]
What's the error you get when you don't use optimizeDeps? It's likely an issue on Vite's side.

**Comment by charlieforward9** [comment]
Thats awkward... I removed the snippet and it didn't break... Ill leave it commented out in case it returns...

**Comment by brillout** [comment]
Vite's optimizeDeps is prone to race conditions. It could be a Vite bug.

**Comment by charlieforward9** [comment]
Ill keep this issue handy if anything pops up again. Thanks

**Comment by chris-m92** [comment]
Thanks for working on this. I don't use Vite so unfamiliar with the warnings you were getting.

If you find a fix that will also not interfere with CRA, feel free to make a PR.
